spring:
  datasource:
    url: jdbc:mysql://119.3.13.230:3306/SpringBootTest?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 6282381xuhaohan@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080